"""First migration

Revision ID: f260205863d2
Revises: f59e837ad635
Create Date: 2021-05-26 10:02:33.035460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f260205863d2'
down_revision = 'f59e837ad635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cleanings', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.execute("UPDATE cleanings SET price=0.00")
    op.alter_column('cleanings', 'price', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cleanings', 'price')
    # ### end Alembic commands ###
